### ISSUE TITLE
FAST autocomplete is broken

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1916]
Maybe broke as part of our vite migration?

When I type in the should-be-autocompleted `subject` field on production, I get this JS error in dev console:

```
5qa_autocomplete.js:56 Uncaught TypeError: o.autocomplete is not a function
    at Vi (qa_autocomplete.js:56:14)
    at HTMLInputElement.<anonymous> (qa_autocomplete.js:124:7)
    at HTMLBodyElement.dispatch (jquery.js:5430:27)
    at N.handle (jquery.js:5234:28)
    at Object.trigger (jquery.js:8745:12)
    at Object.simulate (jquery.js:8814:16)
    at HTMLDocument.n (jquery.js:8848:17)
```

**Comment by jrochkind** [comment]
Hm, the file that implements autocomplete does a:

`import 'devbridge-autocomplete';`

Under webpacker, that was enough to make a jquery `.autocomplete()` function available.  Under vite it appears not to be, not sure why or how to fix, looking into it.

**Comment by jrochkind** [comment]
https://github.com/devbridge/jQuery-Autocomplete/issues/843

**Comment by jrochkind** [comment]
Hm.  We could copy and paste that jquery plugin to a local file, and edit it's loading code to work. 

We could switch to a whole different autocomplete implementation (that one isn't very actively maintained, and requires jquery; although it works well).  Blacklight just switched to: https://github.com/github/auto-complete-element

That one uses "web components" so requires some change to markup, a little bit of work to switch to it... although probably it would work?

**Comment by jrochkind** [comment]
Huh, while it also hasn't been maintained in forever, there may be a non-jQuery autocomplete alternative from the same source that may import properly and require few code changes....

https://github.com/devbridge/Vanilla-Autocomplete

**Comment by jrochkind** [comment]
Another one we could maybe switch to in future: https://github.com/digitalfortress-tech/typeahead-standalone
