### ISSUE TITLE
Remove n+1 from download options parent lookup

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2378]
When we added the zip link to the individual asset download options, with these lines:

https://github.com/sciencehistory/scihist_digicoll/blob/a36e8f1e085be41c2d75ccc94c54e600735248a9/app/presenters/download_options/image_download_options.rb#L24-L28

We added an example of what can be generally called an "n+1 query problem" to our page -- _every_ ImageDownloadComponent on a page (one per thumbnail) repeats this query, potentially going to the database one time for each thumbnail. 

It turns out Rails saves this from happening with a per-request "query cache", as evidenced by below log lines. Which keeps it from being catastrophic. But it's still sloppy and a bit fragile -- and also leads to all those log lines in dev, which is annoying!

```
  CACHE Kithe::Model Count (0.0ms)  SELECT COUNT(*) FROM "kithe_models" WHERE "kithe_models"."parent_id" = $1  [["parent_id", "9a5614e3-d2a2-4278-86ed-2deede5c586c"]]
  ↳ app/presenters/download_options/image_download_options.rb:24:in `options'
  CACHE Kithe::Model Count (0.0ms)  SELECT COUNT(*) FROM "kithe_models" WHERE "kithe_models"."parent_id" = $1  [["parent_id", "9a5614e3-d2a2-4278-86ed-2deede5c586c"]]
  ↳ app/presenters/download_options/image_download_options.rb:24:in `options'
  CACHE Kithe::Model Count (0.0ms)  SELECT COUNT(*) FROM "kithe_models" WHERE "kithe_models"."parent_id" = $1  [["parent_id", "9a5614e3-d2a2-4278-86ed-2deede5c586c"]]
  ↳ app/presenters/download_options/image_download_options.rb:24:in `options'
```

(repeat once per thumb on page). 

This is actually a general problem that comes up with our component-based architecture for displaying thumbs, I've had this problem before, where it's hard to figure out how to get "state" information down a component tree. 

In this case, I can think of two alternative sensible solutions:

1.  Pass in a "should show zip link" param to the ImageDownloadOptions component -- it's caller, the DownloadDropdownComponent already has the state it needs to decide this. (not preferred, see number 2)
2. Just have DownloadDropdownComponent add the zip link on to what ImageDownloadOptions provides -- DownloadDropdownComponent already knows what it wants to do and has that state, to decide to for instance _not_ show the "whole work" download options int eh first place. 

2 sounds good, except, oops, I ssee searching we also call ImageDownloadOptions from `ViewerMemberInfoSerializer`... this is a bit of a mess! 

Maybe there's some other solution too with some kind of a global state object which gets passed down, or pass in the `work` too (so all the ones on a page will have the _same_ work, and when you ask it for it's `parent`, that will only be queried _once_ cause the `work` will be the same and remember it). 

In general, this kind of problem has been a confusing and hard to deal with one in this component-based thumbnail-display and download-options architecture. 

Once solved, we could and maybe should also turn on [Rails strict-loading](https://blog.saeloun.com/2020/02/25/rails-strict-loading-mode-to-fix-n-1/) feature for the objects involved when they are fetched, which would result in this kind of n+1 problem raising and not making it out of test/dev. 

Cc @eddierubeiz

**Comment by jrochkind** [comment]
Complexified further cause I'm working on actually _removing_ the PDF link from the download dropdown in some cases! 

Which the new logic for in ImageDownloadLinks makes somewhat more complicated. 

I may try to refactor this first....

**Comment by jrochkind** [comment]
huh, we already ARE setting `strict_loading`, via


https://github.com/sciencehistory/scihist_digicoll/blob/a36e8f1e085be41c2d75ccc94c54e600735248a9/app/models/work.rb#L130-L143

via

https://github.com/sciencehistory/scihist_digicoll/blob/a36e8f1e085be41c2d75ccc94c54e600735248a9/app/components/work_image_show_component.rb#L44-L46

Very odd, I'm not sure what's going on.

**Comment by jrochkind** [comment]
I guess `strict_loading` does not apply to `count` queries!

**Comment by jrochkind** [comment]
This is a super weird one. 

Asset `asset.parent.members` does not raise despite `strict_loading`, which should mean that `members` is loaded. 

In cases wehre members is loaded, `asset.parent.members.size` should be the equivalent of `asset.parent.members.length` -- and not execute a SQL query, just take the length of the in-memory array. 

BUT... it does an SQL anyway!

`asset.parent.members.count` will do an SQL query either way -- and we see it do that. But `size` is supposed to be the clever way out of that -- doing a SQL query if the association _isn't_ already loaded, but just doing `length` of in-memory array if it is... 

I can't figure out what's going on, this stuff is way too convoluted. But since I need the ability to control whether PDF link is displayed explicitly, regardless of work properties, anyway...  for #2372.... I see an alternate way out.

**Comment by jrochkind** [comment]
handled this with #2386
