### ISSUE TITLE
Problem with fixity check rake task.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#380]
See also: https://app.honeybadger.io/projects/58989/faults/53084230
`eddie@kithe-jobs1-staging:/opt/scihist_digicoll/current$ bundle exec rake "scihist:check_fixity"` currently yields:

```
Traceback (most recent call last):
        11: from /usr/local/bin/bundle:10:in `<main>'
        10: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:42:in `require'
         9: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
         8: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
         7: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:303:in `to_specs'
         6: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:284:in `matching_specs'
         5: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:59:in `filter!'
         4: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:16:in `bundler_version'
         3: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:33:in `bundler_version_with_reason'
         2: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `lockfile_version'
         1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:97:in `lockfile_contents'
/usr/local/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:97:in `pwd': No such file or directory - getcwd (Errno::ENOENT)```

**Comment by eddierubeiz** [comment]
This is not reproducible in staging with the latest version of either master or the fixity reporting branch.
With a couple days' hindsight and a little detective work, I'm now guessing this isn't a real problem and was probably caused by my running `bundle exec rake "scihist:check_fixity"` in side a directory that no longer existed, because I deployed to staging more than 5 times -- hence the failure of `getcwd`.

**Comment by eddierubeiz** [comment]
If we *ever* see this bug again we can reopen this ticket. I suspect we won't. Moving on.
